### ISSUE TITLE
mdbx_cursor_open: MDBX_THREAD_MISMATCH

### ISSUE THREAD

**Issue by leonardyp** [ledgerwatch/erigon-lib#410]
Hello everyone，Can someone tell me how to deal with this bug？ Thanks ！

**"table: PlainState, mdbx_cursor_open: **MDBX_THREAD_MISMATCH**: A thread has attempted to use a not owned object, e.g. a transaction that started by another thread"**

**Comment by AndreaLanfranchi** [comment]
You're using a transaction in thread B when it was originally opened in thread A
